# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38faf7e0b154726789e234ee8c3b7c608cf3062d4b2b1d44298bf043068182ed187e96d54dfc5fd7004378add0d7e23693851986e458593e2671cfcab6b3d40

test:
  secret_key_base: 66ced4e49f14b4b2f4696ba5e4cd4dcea1d15881c636ffb57103e7e80a5256fcdf86595efe79f5d3d9451aa78afd184b2851135d9977401303fe54dae7b36ece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
